# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincSMS', '0002_auto_20161107_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='notifications',
        ),
        migrations.AddField(
            model_name='userdata',
            name='apy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='lpg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='ny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='ratio',
            field=models.BooleanField(default=False),
        ),
    ]
