# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fincSMS', '0003_auto_20161107_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='ratio',
            new_name='ration',
        ),
    ]
