# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincSMS', '0004_auto_20161107_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='employed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
